// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC5aiTLnJH-3v3igOpbuhnOSh5eM_WO4A',
    appId: '1:989229633801:web:39ed2c97b5523d379ec3d8',
    messagingSenderId: '989229633801',
    projectId: 'weather-desktop-b4af3',
    authDomain: 'weather-desktop-b4af3.firebaseapp.com',
    storageBucket: 'weather-desktop-b4af3.firebasestorage.app',
    measurementId: 'G-19PDP4FVB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABUHg7RFB_eJ79kHt5PgeqTLMqAMpqy8o',
    appId: '1:989229633801:android:cba012ba87f9475f9ec3d8',
    messagingSenderId: '989229633801',
    projectId: 'weather-desktop-b4af3',
    storageBucket: 'weather-desktop-b4af3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUdeebwxnjb40hyoi4tBki_H83JX_Txnc',
    appId: '1:989229633801:ios:45acde917f3178669ec3d8',
    messagingSenderId: '989229633801',
    projectId: 'weather-desktop-b4af3',
    storageBucket: 'weather-desktop-b4af3.firebasestorage.app',
    iosBundleId: 'com.example.weatherDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUdeebwxnjb40hyoi4tBki_H83JX_Txnc',
    appId: '1:989229633801:ios:45acde917f3178669ec3d8',
    messagingSenderId: '989229633801',
    projectId: 'weather-desktop-b4af3',
    storageBucket: 'weather-desktop-b4af3.firebasestorage.app',
    iosBundleId: 'com.example.weatherDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC5aiTLnJH-3v3igOpbuhnOSh5eM_WO4A',
    appId: '1:989229633801:web:611f129b30264ad79ec3d8',
    messagingSenderId: '989229633801',
    projectId: 'weather-desktop-b4af3',
    authDomain: 'weather-desktop-b4af3.firebaseapp.com',
    storageBucket: 'weather-desktop-b4af3.firebasestorage.app',
    measurementId: 'G-Q0CXCBJ9WY',
  );
}
